get_state:
  name: Get Sunlight State
  description: Calculates solar coverage and blinds state with hysteresis and lux measurement.
  fields:
    window_azimuths:
      name: Window Azimuth(s)
      description: Single azimuth (e.g. 110) or range list [40, 135].
      example: [40, 135]
      selector:
        object:
    lum:
      name: Illuminance (Lux)
      description: Direct float lux value or template variable.
      example: 10500
      selector:
        number:
          min: 0
          max: 150000
          mode: box
    previous_state:
      name: Previous State
      description: Current state of the blind to apply hysteresis.
      default: "open"
      selector:
        select:
          options:
            - "open"
            - "side"
            - "slightly"
            - "direct"